apiVersion: v1
kind: Secret
metadata:
  name: acr-credentials
  namespace: flux-system
type: Opaque
stringData:
  username: "a74bb5f1-70ab-4e43-804f-911563937a5b"
  password: "YOUR_AZURE_CLIENT_SECRET"
