apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-flux-tenant
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/devopsrakesh29/app_flux_tenant.git
  ref:
    branch: main
