apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: axion-ui
  namespace: int
spec:
  interval: 5m
  chart:
    spec:
      chart: axion-ui
      version: ">=0.1.0"
      sourceRef:
        kind: HelmRepository
        name: acr-helm-repo
        namespace: flux-system
      valuesFiles:
        - values-int.yaml
